version: 3

tasks:
  install:
    desc: Install dependencise
    deps: [venv]
    cmds: 
      - poetry install
      - playwright install-deps  
      - playwright install
  dev:
    desc: Launch the server
    dir: src/wall_e
    cmds:
      - poetry run uvicorn main:app
  venv:
    desc: Launch virtual environement
    cmds:
      - poetry env use 3.12